### PR TITLE
Added a definition for 'current document'

### PR DESCRIPTION
**Pull request by plehegar**

### CODE REVIEW

**Comment by igrigorik** [comment]
LGTM, but would love to get @bzbarsky or @annevk to sanity check.

**Comment by annevk** [comment]
Shouldn't this talk about the "active document"?

**Comment by bzbarsky** [comment]
No, "active document" wouldn't do the right thing; that's a concept associated with a browsing context, not with a global.

The big problem I have with the proposed wording is that unlike every single other thing in the platform it seems to use the term "document" to refer to something other than a `Document` object (though it's "associated" with one?), and I'm not sure what that something is, exactly...

**Comment by plehegar** [comment]
My understanding is as follows:
- each  environment settings object has one global object, one responsible browsing object, and, by extension, one active document.
- the case where the document is replaced within the same browsing object isn't really relevant here since it happens on about:blank and we don't expect timing APIs to be active for that.
- we attach ourselves to the global object since a document can be attached to more than one browsing context.

We need to define what 'current document' means in our time origin definition:
"If the global object is a Window object, the time origin must be equal to the time of starting the navigation responsible for loading the current document, unless a confirmation dialog is displayed during the prompt to unload algorithm, in which case the time of the user confirming the navigation must be used instead. If there is no previous document, the time origin must be equal to the time when the browsing context is first created."

As such, it's not clear to me that there is a difference between active document and "the Window object's newest Document object."

The term document is used in instance like "Each document has a current document readiness", that's why I felt comfortable using it but it could easily be dropped, ie

"The term current document refers to the Window object's newest Document object."

**Comment by bzbarsky** [comment]
>  each environment settings object has one global object, one responsible browsing object, and, by
>  extension, one active document.

While true, why does that matter?  The active document can well be associated with a different global than the environment settings object in question, right?  Please just don't think about active document here.

> the case where the document is replaced within the same browsing object isn't really relevant here
> since it happens on about:blank

I have no idea what you're trying to say there....

> since a document can be attached to more than one browsing context

Nor here.

> As such, it's not clear to me that there is a difference between active document and "the Window
> object's newest Document object."

There totally is.  Consider a browsing context that loads a page A, then unloads A and loads B.  Now a function from A is called.  The global in that function is the Window of A.  The current document is B.

Or to put this in code terms:

    <!DOCTYPE html>
    <iframe src="A.html"></iframe>
    <script>
    onload = function() { 
      var funcFromA = frames[0].someFunction;
      document.querySelector("iframe").onload = function() {
        funcFromA();
      };
      frames[0].location = "B.html";
    }
    </script>

When `funcFromA` runs, the active document in its `Window`'s browsing context is the one created when B.html was loaded.  The `Window` associated with `funcFromA` is the one created when A.html was loaded.

So we do want something like the "current document" concept; this spec gets that right.  And we want it defined in HTML, because other specs need it too (e.g. https://w3c.github.io/requestidlecallback/ wants the same concept; it's currently incorrectly using "active document").  That will allow us to have a clear definition of the "current document" of a `Window`, since HTML can just define in the processing model when it gets updated.

Again, my issue is with the use of the term "document" to refer to something other than a `Document` object in this spec, and the lack of clarity about what that something is.

**Comment by toddreifsteck** [comment]
Per discussion at TPAC, update to The term <dfn>current document</dfn> refers to the Document object returned by Window.document and add a link to https://github.com/whatwg/html/issues/270 then we are good to merge.

**Comment by bzbarsky** [comment]
Why do you need a new term for what already has a perfectly good term in the HTML spec?  It's called the " the Window object's newest Document object".

Again, the problem I have with the pull request here is that it uses "document" to mean something other than a `Document` object altogether....

**Comment by plehegar** [comment]
ok, latest proposed commit removed the mention of "current document" in the time origin definition and now uses "the Window object's newest Document object" instead.

**Comment by toddreifsteck** [comment]
The newest version LGTM. @bzbarsky @igrigorik ?

**Comment by igrigorik** [comment]
LGTM

**Comment by toddreifsteck** [comment]
Per 11/11 call, we are merging. @bzbarsky please let us know if there are still issues.

**Comment by toddreifsteck** [comment]
Per Philippe, he would prefer to squash before merging. Sorry for the noise.

**Comment by bzbarsky** [comment]
The text in https://github.com/w3c/hr-time/commit/a3a8c9147c927316bbb491284c30004a08720f75 looks ok, though it might be clearer to get the "no previous document" case out of the way first before talking about various things that are not applicable in that case.  The current structure of the text is basically: Do X.  If Y do Z (with an implied "instead of X" which is never made explicit).  It would be clearer if it said: If Y do Z, otherwise do X.

**Comment by plehegar** [comment]
I opened a separate pull request to reword the time origin definition. See https://github.com/w3c/hr-time/pull/19

**Pull request merged**
