### PR TITLE
Add a <dfn> for "high resolution time"

### LINKED ISSUE #88: High resolution time is not defined
It seems this should have a dfn somewhere.

### PR DESCRIPTION
**Pull request by mmocny**
Fixes #88

***
<a href="https://pr-preview.s3.amazonaws.com/mmocny/hr-time/pull/94.html" title="Last updated on Sep 15, 2020, 2:16 PM UTC (9b9f55f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/94/c2cb506...mmocny:9b9f55f.html" title="Last updated on Sep 15, 2020, 2:16 PM UTC (9b9f55f)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
Are all these values basically global to the user agent, including time origin? Or are they scoped to something else but that's not stated?

**Comment by mmocny** [comment]
I should have fixed the issue with ipr by linking my github account, but Repository Manager is now failing to fetch the details of this PR so I cannot poke it to revalidate right now...

**Comment by mmocny** [comment]
@annevk looking at it more closely, it looks like there may not need be any use for a definition for "high resolution time".  Instead, the few current references to it should be replaced with references specifically to `{{DOMHighResTimeStamp}}` or to specific algorithms (such as those in timeOrigin section, which describe scope relation to global object).

(The algorithms also need improvement.  Changes incoming.)

**Comment by annevk** [comment]
DOMHighResTimeStamp doesn't really mean anything on its own though. It's just a typedef for a number. Something needs to define what number that is.

**Comment by yoavweiss** [comment]
What we discussed was to always return that number as a result of a well-defined algorithm, that would include the description part that "high resolution time" currently conveys. Would that work from your perspective?

**Comment by annevk** [comment]
Yeah, that sounds good.

**Comment by yoavweiss** [comment]
@mmocny - can you rebase now that https://github.com/w3c/hr-time/pull/95 has landed?

**Comment by yoavweiss** [comment]
> I should have fixed the issue with ipr by linking my github account, but Repository Manager is now failing to fetch the details of this PR so I cannot poke it to revalidate right now...

Clicked the button and the bots seem happy now :)

**Comment by mmocny** [comment]
Since #95 and #96 has evolved the plan here, I'll just close this PR for now.  I think it'll need a substantively different resolution (and possibly no longer need a `<dfn>`)

**Pull request closed without merging**
