### PR TITLE
Test driven

### PR DESCRIPTION
**Pull request by plehegar**
See
  https://lists.w3.org/Archives/Public/public-web-perf/2017Mar/0023.html
  https://lists.w3.org/Archives/Public/public-web-perf/2017May/0003.html

Also attempting to reuse https://w3c.github.io/spec-labels.html

@foolip @yoavweiss

### CODE REVIEW

**Comment by plehegar** [comment]
(once this one gets merged, I'll apply the same changes to all webperf repos)

**Comment by igrigorik** [comment]
Would it make sense to pull this out into a centralized document on contributing to all spec work done in the group? I'm wary of duplicating this (and having to update it) across every single repo..

**Comment by foolip** [comment]
I've thought about creating some standalone document as well, but see two issues:
* Need a standards org-neutral place to host it, the best I've come up with would be a personal GitHub repo of whoever writes it, like https://github.com/tabatkins/bikeshed.
* If people reference it as "we follow this process", then when changing it one would still have to make sure that the referencing groups are OK with it.

So, I'm inclined to spread this a bit further (perhaps duplicating 5-10 times) before generalizing, and volunteer to generalize it once enough people ask for it.

**Comment by igrigorik** [comment]
I was thinking of scoping it to this group specifically (I imagine different groups will have different policies and workflows), and hosting it on https://github.com/w3c/charter-webperf?

**Comment by foolip** [comment]
Yeah, that would work. https://github.com/whatwg/html/blob/master/CONTRIBUTING.md points to https://github.com/whatwg/meta/blob/master/CONTRIBUTING.md in a similar fashion.

I imagine that people will want to de-duplicate even further, but I'm happy to punt on that.

**Comment by plehegar** [comment]
for webperf, we could put a file in https://github.com/w3c/web-performance/ and then link to that from all webperf repos. I'll make a PR for that effect.
Regarding a more general use, I indicated to the W3C AC last week that I intend to shift all W3C groups towards early testing. I also agree that we need to build more experience on the way to it since there are still some open questions (such as how early do you start?).

**Comment by igrigorik** [comment]
sgtm. should we close this PR then?

**Comment by plehegar** [comment]
See also https://github.com/w3c/web-performance/pull/17

**Pull request merged**
