### PR TITLE
Expose everywhere

### PR DESCRIPTION
**Pull request by Ms2ger**
Ref: https://github.com/tc39/proposal-shadowrealm/issues/331

Implementation commitment - primarily for "change" and other normative changes: Positive initial signals from Google, Apple, Mozilla on the general direction.

- [ ] [WebKit]()
- [ ] [Chromium]()
- [ ] [Gecko]()

Tasks:

- [ ] [Added tests](https://github.com/web-platform-tests/wpt/pulls/???)

***
<a href="https://pr-preview.s3.amazonaws.com/Igalia/hr-time/pull/130.html" title="Last updated on Nov 4, 2021, 11:00 AM UTC (11f840c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/130/f1d5dd4...Igalia:11f840c.html" title="Last updated on Nov 4, 2021, 11:00 AM UTC (11f840c)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
The next release of ReSpec will include support for this (via WebIDL2.js)... should be landing in the next 24 hours.

**Comment by saschanaz** [comment]
Somehow spec-prod still gets the previous version of webidl2.js and I wonder it implicitly uses a cache for `yarn add`? @sidvishnoi

**Comment by sidvishnoi** [comment]
@saschanaz 
> Somehow spec-prod still gets the previous version of webidl2.js and I wonder it implicitly uses a cache for yarn add? 

spec-prod doesn't cache dependencies (not webidl2.js at least). Can you share where you found it being cached?

Current build error seems to be a regression in ReSpec (marked is not a function). Will send a fix and release soon.

**Comment by saschanaz** [comment]
Tried on my fork: https://github.com/saschanaz/hr-time/runs/4119110069?check_suite_focus=true

I don't see `marked` issue there, but only the validation failure.

**Comment by sidvishnoi** [comment]
webidl2 error occurred as an older version got installed in a previous step with `yarn add reffy`. `yarn add webidl2` just decided to use the one available instead of latest as an optimization (yarn's optimization as we didn't ask for specific version). Will use `webidl2@latest` instead.

> BTW, probably useful if it shows which version of the library is installed.

Good point, will add. spec-prod does show for respec/bikeshed, but not for other libraries.

**Comment by saschanaz** [comment]
Now yarn [argues that it gets webidl2@24.2.0](https://github.com/saschanaz/hr-time/runs/4123103853?check_suite_focus=true) but still fails to parse the IDL. Not sure what's happening, since ReSpec itself can now parse it properly with that version.

**Comment by sidvishnoi** [comment]
@saschanaz Should be ok now with [v2.6.5](https://github.com/w3c/spec-prod/releases/tag/v2.6.5)

**Comment by saschanaz** [comment]
Thanks! Things are definitely not simple 😭

**Comment by saschanaz** [comment]
Since it now runs well [in my fork](https://github.com/w3c/hr-time/runs/4104067183?check_suite_focus=true), probably someone with proper access should rerun the job and then everything should be okay.

**Comment by marcoscaceres** [comment]
Re-running…

**Comment by Ms2ger** [comment]
This should be ready to merge now; I'll submit tests to WPT once the IDL changes have propagated from webref.

**Comment by Ms2ger** [comment]
Hey @yoavweiss, is there anything I need to do on my side to move this along?

**Comment by marcoscaceres** [comment]
Merging as it was approved! Thanks for the poke @Ms2ger!

**Pull request merged**
